### ISSUE TITLE
The entity is no longer being provisioned by the robovac integration

### ISSUE THREAD

**Issue by LarveyOfficial** [CodeFoodPixels/robovac#17]
I keep getting this error whenever using the robovac integration. Seems to be fine for a while after setup. Then this happens
![Screenshot_20230829-093323_Home Assistant.png](https://github.com/CodeFoodPixels/robovac/assets/39219859/d5de9f37-ac22-46ac-8027-784777847714)

**Comment by LarveyOfficial** [comment]
For more context.
I am using a LR20 with the newest version of HASS container and on 1.1.0-beta.1 for the version of the integration

**Comment by CodeFoodPixels** [comment]
Anything in the logs?

**Comment by LarveyOfficial** [comment]
Issue seems to be fixed in newer versions, but now I cant even use the vacuum due to #18
