### ISSUE TITLE
Non-functional buttons

### ISSUE THREAD

**Issue by ATaylor5596** [CodeFoodPixels/robovac#20]
Since those fork looks like it will actually be supported long term hopefully we can get a fix to a few issues. For the X8 the c0ntrol buttons font seems to work or only half work. The play/pause button on the vacvum card, when you press it, it will start the vacuum but if you press it again to pause it it will instead stop the cleaning and put it into Standby mode instead. As for the control buttons in the entity itself, they don't seem to work at all, pressing them doesn't stop, locate, spot clean or anything. Is there any chance of solving these issues?

**Comment by CodeFoodPixels** [comment]
Are you using the default vacuum card?

**Comment by ATaylor5596** [comment]
The mushroom vacuum card. I do want to make a quick amendment to what I said, the stop button and return button do work, but still the other locate, play/pause and spot clean buttons do not work (though without the UI of the app I'm not sure if the spot clean button is supposed to work all)

**Comment by CodeFoodPixels** [comment]
Can you try the default vacuum card please?

**Comment by ATaylor5596** [comment]
Okay, tried with the default card, pause still puts the vacuum into standby, it doesn't pause the cleaning cycle, and stop returns to the docking station instead of putting it into standby mode.

**Comment by CodeFoodPixels** [comment]
@ATaylor5596 could you run this and paste the output here please?

**Comment by ATaylor5596** [comment]
Sorry for the delay, here is the result of the script

Logging in to Eufy
    Success
Getting Eufy device info
    Success
Devices
    Cleaning device: RoboVac (REDACTED)
        Found device in tuya
            eufy RoboVac X8-v8pp
            [{"attr":0,"canTrigger":true,"code":"power","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","iconname":"icon-dp_power2","id":1,"mode":"rw","name":"电源开关","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"power_go","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","iconname":"icon-dp_power","id":2,"mode":"rw","name":"清扫开关","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"direction","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","iconname":"icon-dp_mode","id":3,"mode":"rw","name":"清扫方向","property":{"range":["forward","back","left","right"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"mode","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","iconname":"icon-dp_dust","id":5,"mode":"rw","name":"清扫模式","property":{"range":["auto","room","zone","spot"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"status","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","iconname":"icon-dp_direction","id":15,"mode":"ro","name":"工作状态","property":{"range":["standby","Running","Sleeping","Recharge","Charging","completed","Goto","Locating"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"auto_recharge","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":101,"mode":"rw","name":"自动回充","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"cleaning_strength","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":102,"mode":"rw","name":"清扫强度","property":{"range":["Max","Turbo","Standard","Quiet","speed5","speed6"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"look_for_sweeper","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":103,"mode":"rw","name":"寻找扫地机","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"bat_level","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":104,"mode":"ro","name":"剩余电量","property":{"unit":"","min":0,"max":100,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"mop","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":105,"mode":"rw","name":"拖地设置","property":{"range":["MopHigh","MopMiddle","MopLow"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"fault_report","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":106,"mode":"ro","name":"故障提示","property":{"unit":"","min":0,"max":10000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"ForbidMode","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":107,"mode":"rw","name":"勿扰模式状态","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"robo_pos","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":108,"mode":"ro","name":"机器人位姿","property":{"type":"string","maxlen":255},"type":"obj"},{"attr":0,"canTrigger":true,"code":"ClearTime","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":109,"mode":"ro","name":"当前清扫时长","property":{"unit":"s","min":0,"max":10000000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"ClearArea","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":110,"mode":"ro","name":"当前清扫面积","property":{"unit":"M²","min":0,"max":200000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"Loudness","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":111,"mode":"rw","name":"音量调节","property":{"unit":"","min":0,"max":100,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"areaClean","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":116,"mode":"rw","name":"耗材管理","type":"raw"},{"attr":0,"canTrigger":true,"code":"mapMultiFloors","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":117,"mode":"rw","name":"地图多楼层","type":"raw"},{"attr":0,"canTrigger":true,"code":"BoostIQ","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":118,"mode":"rw","name":"自动增压","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"ClearTotalTime","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":119,"mode":"ro","name":"清扫总时长","property":{"unit":"s","min":0,"max":10000000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"ClearTotalArea","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":120,"mode":"ro","name":"清扫总面积","property":{"unit":"m2","min":0,"max":10000000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"mapData","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":121,"mode":"wr","name":"地图流控制","type":"raw"},{"attr":0,"canTrigger":true,"code":"pause_start","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":122,"mode":"rw","name":"暂停/继续","property":{"range":["Nosweep","Pause","Continue"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"languageSet","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":123,"mode":"rw","name":"语言包设置","type":"raw"},{"attr":0,"canTrigger":true,"code":"mapOperations","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":124,"mode":"rw","name":"地图操作","type":"raw"},{"attr":0,"canTrigger":true,"code":"waitRawDP","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":125,"mode":"rw","name":"语音包状态","type":"raw"},{"attr":0,"canTrigger":true,"code":"cleanSetting","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":126,"mode":"rw","name":"清扫设置","type":"raw"},{"attr":0,"canTrigger":true,"code":"langueChange","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":128,"mode":"rw","name":"语言切换","property":{"range":["default","used"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"mopStatus","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":129,"mode":"ro","name":"有无拖布","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"suctionFlag","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":130,"mode":"rw","name":"预约清扫强度","property":{"range":["Max","Turbo","Standard","Quiet","speed5","speed6"],"type":"enum"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"remoteControl","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":131,"mode":"rw","name":"遥控模式状态","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"onceCleanTimes","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":132,"mode":"ro","name":"单次清扫后时长","property":{"unit":"s","min":0,"max":1000000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"onceCleanAreas","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":133,"mode":"ro","name":"单次清扫后面积","property":{"unit":"m2","min":0,"max":10000000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"onceCleanCout","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":134,"mode":"ro","name":"单次清扫次数","property":{"unit":"","min":0,"max":100000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"waiteBoolDP01","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":135,"mode":"rw","name":"断点续扫开关","property":{"type":"bool"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"remind_code","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":137,"mode":"ro","name":"扫地机提醒","property":{"unit":"","min":0,"max":10000000,"scale":0,"step":1,"type":"value"},"type":"obj"},{"attr":0,"canTrigger":true,"code":"waiteDPRaws","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":139,"mode":"rw","name":"勿扰模式设置","type":"raw"},{"attr":0,"canTrigger":true,"code":"Log","defaultRecommend":false,"editPermission":false,"executable":true,"extContent":"","id":142,"mode":"rw","name":"日志","type":"raw"}]
Test script ran successfully

**Comment by CodeFoodPixels** [comment]
Closing this in favour of #28
