### ISSUE TITLE
Broken since August 2023 HA update 

### ISSUE THREAD

**Issue by wBrhy2** [CodeFoodPixels/robovac#22]
Since I updated my HA  in August 2023, the vacuum card I was using is no longer available, so I can't press the play/pause button that used to work ,and my script for calling that start/pause function no longer works .

I've made sure the configuration / ip was good as it had changed, but it did not fix anything. Now I can't send any valid commands to my G30 vacuums.

Ps. Huge thanks for taking over the project!

**Comment by wBrhy2** [comment]
I have version 2.0.0 of the HACS EUFY Robovac add-in.

For the card, I think it was the built-in HA one, but can't be sure as I deleted it from my dashboard (thinking maybe removing and re-adding would fix it) and I can't find how to re-add it.

**Comment by wBrhy2** [comment]
Ah! it was the lovelace vacuum card v 2.7.6 by https://github.com/denysdovhan I'll look further into that!

**Comment by CodeFoodPixels** [comment]
Are you sure you have this repository added to HACS? I've only released 1.0.0 and some beta versions, we don't have a version 2.0.0

**Comment by wBrhy2** [comment]
> Are you sure you have this repository added to HACS? I've only released 1.0.0 and some beta versions, we don't have a version 2.0.0

Oh good point. Let me uninstall the old one and install yours! I was still running off the version you forked from.

**Comment by wBrhy2** [comment]
Okay, so deleting the cards, and re-installing the HACS card and integration, then re-adding the entity and then selecting the vacuum card fixed it.
