### ISSUE TITLE
[Feature Request] Make metrics like battery a `sensor`

### ISSUE THREAD

**Issue by 8none1** [CodeFoodPixels/robovac#23]
Caveat:  I find the home assistant data model to be quite confusing, so maybe this is already possible and I just don't know how to use it.

The robovac entity `vacuum.foo` has a number of attributes that I would find interesting & useful to be able to graph over time.  For example, battery.  I could spot when the battery is draining faster that it used to and so perhaps needs to be replaced.

These metrics are currently stored as attributes against the main `vacuum` entity.  In other devices where the data is exposed in the way I would like the main entity provides a number of seperate `sensors` which hold that information.  When I click on them I am able to see a graph.

I think `battery` is the only one I really need.

Thanks for picking up this project and resurecting it.  Much appreciated.

**Comment by CodeFoodPixels** [comment]
This sounds like a great idea, I'll have a look at this

**Comment by CodeFoodPixels** [comment]
If you download the `main` branch, I've added a sensor for battery if you'd like to give it a try?

**Comment by 8none1** [comment]
Great success!

![image](https://github.com/CodeFoodPixels/robovac/assets/6552931/518ca5bf-7f63-48f4-b18a-0074f19e1571)

![image](https://github.com/CodeFoodPixels/robovac/assets/6552931/54f3ba2e-0e5d-4e20-8c11-53fcdbf0c891)

**Comment by 8none1** [comment]
This landed in https://github.com/CodeFoodPixels/robovac/releases/tag/v1.1.1

Closing as complete.  Thank you!
