### ISSUE TITLE
Lr30+ supported?

### ISSUE THREAD

**Issue by scubieman** [CodeFoodPixels/robovac#24]
Trying to add vacuum says successful but doesn't actual add it to the list. Logs show no errors. I have lr30+

**Comment by CodeFoodPixels** [comment]
Which version of the integration are you using?

**Comment by scubieman** [comment]
V1.0.0 Eufy Robovac integration into HACS.

**Comment by CodeFoodPixels** [comment]
The LR30 should be supported in the betas or on main

**Comment by scubieman** [comment]
> The LR30 should be supported in the betas or on main

not sure why im getting this logging message? 

custom_components.robovac.robovac.ModelNotSupportedException: Model T2181 is not supported

**Comment by CodeFoodPixels** [comment]
If you are using 1.0.0, then it is not supported on that version. You need to select "main" or one of the beta versions

**Comment by scubieman** [comment]
Went to main. Got it added, however showing unavailable.


![NVIDIA_Share_U75usni0IX](https://github.com/CodeFoodPixels/robovac/assets/42748871/1ee490bd-269e-4bff-ab7d-1b2a422f3728)

**Comment by CodeFoodPixels** [comment]
Yeah, set the IP in there if it's not automatically picking it up. No idea why the text isn't showing

**Comment by scubieman** [comment]
I think network issue. Device in the config of HA shows mac ending in 6A, the app showing ending 6A. Unifi Showing ending in e8. I also show network IP address is set in the config and static in Unifi.

**Comment by scubieman** [comment]
Do you know how I double check the variable in the system for the ip address of the vacuum?

**Comment by scubieman** [comment]
this is in my core.config_entries. I believe this is correct? I changed some values to secure my stuff. The mac address here does not match whats in the eufy app. But does match whats in unifi

"model": "T2181",
              "name": "super sucker",
              "description": "LR30 Hybrid+",
              "mac": "30:7b:c9:45:XX:XX",
              "ip_address": "192.168.5.25",
              "autodiscovery": true,
              "access_token": "XXXXXXXXX"

**Comment by CodeFoodPixels** [comment]
If you go to settings > system > logs, is there anything from this integration?

**Comment by scubieman** [comment]
Nothing in the logs...Wondering if IP is actually being set or if I should hard code the IP? Not sure how or where?

**Comment by CodeFoodPixels** [comment]
If there's an IP address in your config entries, then the integration should have an IP to use. The only reason that it wouldn't work is if it was the wrong IP.

**Comment by scubieman** [comment]
The MAC address in the app and MAC in UNIFI are different. The MAC in config Entries Matches what's in UNIFI. I will try switching IP once. 
![chrome_kI3KyPWaHo](https://github.com/CodeFoodPixels/robovac/assets/42748871/1151eaae-81db-44ac-9056-83e73339be78)

**Comment by Nicko33127** [comment]
@scubieman sorry for reopening this and thank you for writing down your solution above. After about an hour of trying I managed to get my LR30+ as well into HA, but I wonder if you have managed to add the other functions as the scripts are not for this model?
I am looking for zone cleaning mainly as can clean my downstairs twice this way.

**Comment by scubieman** [comment]
> @scubieman sorry for reopening this and thank you for writing down your solution above. After about an hour of trying I managed to get my LR30+ as well into HA, but I wonder if you have managed to add the other functions as the scripts are not for this model? I am looking for zone cleaning mainly as can clean my downstairs twice this way.

I havent looked into it much since I added it since been busy. At some point I plan on it! if I do ill report back
