### ISSUE TITLE
Robovacs are not found? :(

### ISSUE THREAD

**Issue by qchau77** [CodeFoodPixels/robovac#25]
I followed all the steps but no devices are added. When I hit configure my robovacs show up, but they are not found in the "Devices and Integrations" section. These are all I see, see screenshots.
Do you all know why?
![image](https://github.com/CodeFoodPixels/robovac/assets/145283232/4374c059-2e17-420b-8321-313dc969d7af)
![image](https://github.com/CodeFoodPixels/robovac/assets/145283232/39f1a26d-266e-4549-bd41-01290b3b2edc)

**Comment by CodeFoodPixels** [comment]
Is there anything in the logs?

**Comment by qchau77** [comment]
Also, when I add your repository, should I identify it as an "Integration" in the customer reposition menu?
Thank you for your help.

**Comment by qchau77** [comment]
OMG I installed the beta 4 and everything works now!
