### ISSUE TITLE
[Feature Request] Add Changelogs to HACs Updates

### ISSUE THREAD

**Issue by KyleStilkey** [CodeFoodPixels/robovac#30]
Small little suggestion, would be great to see you add changelogs to the HAC updates to let people know what's changed from within the update prompt.

**Comment by CodeFoodPixels** [comment]
I thought that would have pulled from the GitHub release! I'll have a look
into it

**Comment by CodeFoodPixels** [comment]
Looks like it is pulling through for me.

<img width="627" alt="image" src="https://github.com/CodeFoodPixels/robovac/assets/4780756/dfba0de7-e245-42ec-8ba4-34648d606f3d">

**Comment by KyleStilkey** [comment]
I'll take a look but for me it was just saying version to version without any logs. I would think so too, next push I'll try and keep an eye on it.

**Comment by KyleStilkey** [comment]
Yeah it was an issue on my end, saw the new update and logs. I broke it due to my terrible coding I was doing lol. Not sure why it seemed like it was only this one but I also noticed a few others were missing it and saw it was just me messing with things I shouldn't have been. My bad.
