### ISSUE TITLE
Integration slows down automation when robovac is powered off

### ISSUE THREAD

**Issue by andys73** [CodeFoodPixels/robovac#36]
Hi ,

I just found as problem that was bugging me for a while. I thought it was something wrong with my system. 
The details are in here  https://community.home-assistant.io/t/automation-delays/629820/6
Basically I power off my robovac (my eufy has a physical switch) as the battery consumption is not negligible if the robovac is not in use).
When is off the integration generates errors in the HA core logs and the problem is that it freezes the whole system, automations etc are delayes by 4-6 seconds at times.

`Traceback (most recent call last):
File "/config/custom_components/robovac/tuyalocalapi.py", line 685, in async_connect
sock.connect((self.host, self.port))
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/robovac/tuyalocalapi.py", line 774, in _async_send
await self.async_connect()`

The code should deal more gracefully and not let the system timeout by default.

If no one has time to fix this I can try to do it.

**Comment by thedayofcondor** [comment]
I have the same issue - 1 time out of 3 my robovac gets stuck somewhere overnight, runs out of battery and this integration more or less brings down my entire homeassistant.

**Comment by andys73** [comment]
I made use of the Spook integration https://community.home-assistant.io/t/spook-not-your-homie/539588
This allowed me to disable the device when is off and enable only when I want it on. This also helped with various cameras that are off and they were timing out in home assistant

**Comment by johntr** [comment]
Same issue here. Took me a week to get to the bottom of why my HA kept hanging up randomly. Turns out my device was off. As soon as i turned it back on everything went back to normal.

**Comment by pixelmagic66** [comment]
Same issue here, only the Vac had lost its connection totaly somehow. Needed to delete te vac and reconnect. Before that my HA was VERY slow woth automations and showing screens.

it works great now again but I spend several hours on searching for the reason. Hope it get fixed.

**Comment by CodeFoodPixels** [comment]
I've rewritten the networking stuff, and it seems to be working well. I've been sat here with my vacuum turned off for the past few hours and my HA instance has been solid. I've pushed out an update
