### ISSUE TITLE
How is room cleaning working

### ISSUE THREAD

**Issue by MelleD** [CodeFoodPixels/robovac#47]
I saw there is a room cleaning command. How do I set this and where do I get the rooms ids?
https://github.com/CodeFoodPixels/robovac/blob/main/custom_components/robovac/vacuum.py#L435

**Comment by RoadXY** [comment]
Maybe this helps:
https://community.home-assistant.io/t/eufy-robovac-35c-working-with-home-assistant-updated-11-2020-how-to-guide-now-with-edge-cleaning/152690/293?u=roadxy

**Comment by MelleD** [comment]
Yes this is working and this is what I did. But it was a little bit annoying to test all rooms and figure out the ids.
Maybe there is better way to give the room names.

**Comment by MelleD** [comment]
<img width="402" alt="Bildschirmfoto 2024-01-11 um 15 11 58" src="https://github.com/CodeFoodPixels/robovac/assets/6340898/4c53ad85-35d3-47f0-b232-ce1d3e23b87a">

But after that it works with single or more rooms :)

**Comment by MelleD** [comment]
@RoadXY ah but what I see. Its just working for the first room not for a second room

`{"method":"selectRoomsClean","data":{"roomIds":["3,1"],"cleanTimes":1}`

Room 3 is working but not room 1
