### ISSUE TITLE
Error message not working

### ISSUE THREAD

**Issue by ea5522** [CodeFoodPixels/robovac#5]
Hello,

Thanks for taking over this project. Since the update, the buttons started working. However, the Status just shows as "Error" where before it would actually say what the error was, for example: Rolling Brush Stuck. I have the 30C Max models.

**Comment by cdn4lf** [comment]
@CodeFoodPixels I'm having this issue as well.  The credentials from #2 now authenticate properly, but I'm getting error messages when attempting to execute and commands and the vacuum is showing a status of "Error" as well.

**Comment by hugalafutro** [comment]
SOLVED!
Click configure, add your vacuum's ip everything (i tried so far) works!

![image](https://github.com/CodeFoodPixels/robovac/assets/30209689/0f2ad8d6-25b3-4a8b-8f91-07ebef72e2e9)

**Comment by cdn4lf** [comment]
Confirmed.  This fixed it.

**Comment by pbuckley4192** [comment]
This also worked for me.

**Comment by CodeFoodPixels** [comment]
Because of the update to use the VacuumStateEntity, we can only set the status to certain values. The error itself is reported in the Attributes drop down.

I've also found out that there's a way to do autodiscovery of Robovacs, so I'm going to try and implement that so we don't keep having issues with the IP not being set!

**Comment by CrazyLlamaMan** [comment]
Latest beta fixed all error reporting on my X8.

Thank you for your great efforts.

**Comment by cdn4lf** [comment]
Beta throws an error when trying to use discovery to configure a device setup with IP address.  @CodeFoodPixels , let me know if you want this as a new issue.

**Comment by CodeFoodPixels** [comment]
@cdn4lf Yeah, can you raise it as a separate issue please
