### ISSUE TITLE
Device not added "got an unexpected keyword argument 'access_token'"

### ISSUE THREAD

**Issue by olerap** [CodeFoodPixels/robovac#9]
When trying to set the IP address for my RoboVac, I see this error in the Home Assistant Log:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'access_token'`

The RoboVac doesn't appear in the configuration and thus the setup doesn't work. Any clues?

**Comment by CodeFoodPixels** [comment]
Are you sure you're using this version of the robovac integration and not [bmccluskey/robovac](https://github.com/bmccluskey/robovac)?

That sounds like an error that I fixed when I forked this repo

**Comment by olerap** [comment]
This issue has since been resolved, it suddenly appeared in the integration overnight. Thank you for your work!
