### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by mattmichaels** [CodeFoodPixels/robovac#92]
Hi -

Can't login to the service. Not even getting past the initial login prompt.

I am sure I am entering proper account login information (using a pw mgr, copied pasted the pw) - fails. Tried to remove from HA and re-add; same issue. Invalid authentication.

Am i doing something wrong?

**Comment by SamMousa** [comment]
I just added it for the first time and it works for me. Maybe it was a temporary service interruption?

**Comment by bitzerjd99** [comment]
Same issue for me

**Comment by mattmichaels** [comment]
i have removed and tried to readd, still getting "invalid authentication" 

i tested via browser and was able to login successfully so my credentials are correct and the service is up and running externally

**Comment by mattmichaels** [comment]
was able to login, closing issue.

(i only own x10 pros, so can't go further - lol)

**Comment by damianolombardo** [comment]
I just had this error, it turns out the app automatically truncates passwords to 20 characters without warning, which was not captured by my password manager. If you password is more than 20 characters in your password manager, try only putting the first 20 characters to sign in.

**Comment by Thijs0x57** [comment]
@damianolombardo Yes!! I also just figured out that the password length was the problem. Changed from 32 to 16 characters and now it works.
